services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  php:
    build: ./php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
      - /mnt/media:/var/www/media
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  nginx:
    image: nginx:1.27
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /mnt/media:/var/www/media:ro
    depends_on:
      - php

  varnish:
    hostname: varnish
    image: varnish:7.5
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
      - varnish_shm:/var/lib/varnish
    depends_on:
      - nginx

  varnish-exporter:
    hostname: varnish
    image: jlcox1970/prometheus-varnish-exporter:7.5.0-1
    command:
      - -n
      - /var/lib/varnish/varnishd
    container_name: varnish-exporter
    restart: unless-stopped
    pid: "service:varnish"
    volumes:
      - varnish_shm:/var/lib/varnish
    depends_on:
      - varnish
    expose:
      - "9131"

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    restart: unless-stopped
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /opt/lamp/node_exporter_textfile:/textfile_collector:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/textfile_collector'
    ports:
      - "127.0.0.1:9100:9100"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - node-exporter
    ports:
      - "127.0.0.1:9090:9090"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

volumes:
  db_data:
  prometheus_data:
  grafana_data:
  varnish_shm:
